# Generated by Django 2.2.5 on 2019-09-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='frozen',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
